Better formatting
RPiList/specials pull request #439
Opened 2021-01-03 10:47 UTC by joestr

Improves structure

2021-01-04 06:16 UTC, BulldozerPete requested changes
Bitte alle Pi-hole Standardlisten bis auf die von StevenBlack entfernen.
In der aktuellen Version des Pi-hole wird nur noch diese installiert, da die anderen nicht mehr vorhanden oder aktualisiert werden.

2021-01-04 16:03 UTC, RPiList commented
Hi,

vielen Dank für den Hinweis. 

Wenn aber nur die Standard-Listen entfernt werden sollen, warum werden dann alle "Eigene Listen" ebenfalls gelöscht?

Ich sehe zwar, dass die danach auch wieder erstellt werden, aber in einer anderen Form. Das "Problem" ist, dass die seinerzeit absichtlich so erstellt wurden, damit auch dort das Copy und Paste beim Pi-hole 5 funktioniert. Deswegen hat jede Zeile ein Leerzeichen hinten dran.

Ist das mit der Änderung noch garantiert? Oder hat es im Pi-hole eine Änderung gegeben, dass die neuen Einträge ebenfalls Copy&Paste-kompatible sind?

Viele Grüße

2021-01-05 14:26 UTC, BulldozerPete commented
Verstehe ich jetzt nicht.
Aktuell gibt es nur eine Blockliste, wenn Pi-hole installiert wird. Diese möchte ich gerne unter "Pi-hole Standardlisten" aufnehmen und die alten entfernen. 
Diese sind entweder veraltet oder wurden komplett entfernt. Somit verhindern wir die Aufnahme von Listen, die Fehler werfen oder einen Fehler während der Aktualisierung (pihole- g) ausgeben.

2021-01-05 14:43 UTC, H4ckZ commented
Ich glaube, worauf @RPiList raus will ist folgende Änderung:
![grafik](https://user-images.githubusercontent.com/30937993/103658971-35a4ff00-4f6c-11eb-9cfb-a615275fabee.png)
![grafik](https://user-images.githubusercontent.com/30937993/103659022-405f9400-4f6c-11eb-8f08-2ecbd294c505.png)

Das sind Screenshots vom PR. Da werden die Listen alle "hübscher" aufgelistet.
Die wurden aber ursprünglich deshalb so "in einer Wurst" aufgelistet, da man die Listen so einfach in Bausch und Bogen per Copy&Paste in PiHole importieren kann.
Wenn die Änderung wie in den Screenshots gezeigt übernommen wird müsste man jede Liste einzeln in Pihole importieren.

Daher auch nach jeder URL ein Leerzeichen:
![grafik](https://user-images.githubusercontent.com/30937993/103659447-afd58380-4f6c-11eb-8fb2-649f342dfd9f.png)

2021-01-05 17:46 UTC, closed without merging